services:
  operational_db:
    image: postgres:15
    container_name: operational_db
    environment:
      POSTGRES_DB: operational_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - operational_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - cdc_network

  warehouse_db:
    image: postgres:15
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data
    networks:
      - cdc_network

volumes:
  operational_db_data:
  warehouse_db_data:

networks:
  cdc_network:
    driver: bridge
